In [2]:
import tensorflow as tf

In [ ]:
"""
Тензор - основной тип данных в Tensorflow, представляющий собой n-размерный массив (сильно напоминает numpy.array).
Есть много видов тензоров (фактически бесконечное количество). Тензор, например, может быть скалярным, векторным или
матричным. Это зависит от количества измерений конкретного тензора.
"""

In [3]:
# Скалярный тензор (D-0) - не имеет осей
tensor = tf.constant(4, shape=(), dtype=tf.float32)
tensor

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [13]:
# Векторный тензор (D-1) - имеет одну ось
tensor2 = tf.constant([2., 6., 8.],
                      shape=(1, 3),
                      dtype=tf.float32)
tensor2

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2., 6., 8.]], dtype=float32)>

In [12]:
# Матричный тензор (D-2) - имеет две оси
tensor3 = tf.constant([[1, 2, 3], 
                       [4, 5, 6]], shape=(2, 3), dtype=tf.int32)
tensor3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
# И так далее...

In [14]:
# Тензор, заполненный нулями
tensor_ones = tf.ones((3, 3))

# Тензор, заполненный единицами
tensor_zeros = tf.zeros((5, 5))

tensor_ones, tensor_zeros  # По умолчанию dtype=tf.float32

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>)

In [15]:
# tf.random.normal генерирует случайные значения для тензора
random_tensor = tf.random.normal((3, 3, 5), mean=5, stddev=3)
random_tensor

<tf.Tensor: shape=(3, 3, 5), dtype=float32, numpy=
array([[[ 2.488634 ,  2.110256 , -0.699378 ,  6.68235  ,  5.7396917],
        [ 4.9793425,  4.0027266,  7.0828924,  2.8391833,  2.9980283],
        [ 6.896372 ,  3.8062358,  6.6405134,  5.73829  ,  3.3328493]],

       [[ 6.145818 ,  6.786583 ,  4.6924706,  5.610982 ,  7.355201 ],
        [ 5.144317 ,  8.956663 ,  4.7554865, -0.4891448,  3.6716616],
        [ 3.9293168,  7.4849567,  3.3484106,  4.985854 ,  1.7891603]],

       [[ 2.6198852, -0.7071333,  6.748938 , -2.6166458,  1.2785358],
        [11.587847 ,  8.202044 ,  5.853688 , 11.414026 ,  9.394287 ],
        [ 1.6870449,  7.405337 ,  7.2239966,  5.289405 ,  3.2172449]]],
      dtype=float32)>

In [16]:
random_tensor2 = tf.random.uniform((4, 2, 5), minval=-1, maxval=1)
random_tensor2

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[-0.28735518,  0.28070354,  0.14835691, -0.9812188 ,
          0.38110733],
        [-0.10640383,  0.59192085, -0.17942762,  0.11094522,
         -0.5295062 ]],

       [[ 0.9913497 ,  0.62728167,  0.7738426 ,  0.13127398,
         -0.4484582 ],
        [ 0.63839793, -0.4926958 ,  0.47537518, -0.66377664,
          0.56122136]],

       [[-0.03159523, -0.15863419,  0.30396175,  0.13108706,
         -0.30459142],
        [ 0.19307971,  0.84243107, -0.41738987,  0.37475872,
          0.54456806]],

       [[-0.621932  ,  0.7578113 ,  0.76897955,  0.98208284,
         -0.6040349 ],
        [ 0.13823247, -0.60931754, -0.55199814,  0.135993  ,
         -0.11961365]]], dtype=float32)>

In [17]:
# Аналог range() в tensorflow
tensor_range = tf.range(50)
tensor_range2 = tf.range(start=-60, limit=61, delta=2)  # delta == step

tensor_range, tensor_range2

(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])>,
 <tf.Tensor: shape=(61,), dtype=int32, numpy=
 array([-60, -58, -56, -54, -52, -50, -48, -46, -44, -42, -40, -38, -36,
        -34, -32, -30, -28, -26, -24, -22, -20, -18, -16, -14, -12, -10,
         -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14,  16,
         18,  20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,  42,
         44,  46,  48,  50,  52,  54,  56,  58,  60])>)

In [18]:
# С помощью tf.cast можно конвертировать ТОЛЬКО тип данных тензора
converted_tensor = tf.cast(tf.constant([[34, 61, 7, 5],
                                        [73, 4, 75, 3],
                                        [1, 85, 54, 6]], shape=(3, 4), dtype=tf.int32),
                                        dtype=tf.float32)

converted_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[34., 61.,  7.,  5.],
       [73.,  4., 75.,  3.],
       [ 1., 85., 54.,  6.]], dtype=float32)>

In [28]:
# Математические операции
vector1 = tf.constant([2, 3, 7])
vector2 = tf.constant([5, 4, 8])

# Способ по конвинциям                         Другой способ
tensor_add = vector1 + vector2          # tf.add(vector1, vector2)
tensor_substruct = vector1 - vector2    # tf.substruct(vector1, vector2)
tensor_divide = vector1 / vector2       # tf.divide(vector1, vector2)
tensor_multiply = vector1 * vector2     # tf.multiply(vector1, vector2)

tensor_add, tensor_substruct, tensor_divide, tensor_multiply

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7,  7, 15])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -1, -1])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4  , 0.75 , 0.875])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 12, 56])>)

In [26]:
tensor_by_pow = vector1 ** 5  # Возводоим каждый элемент тензора в пятую степень
tensor_sum = tf.reduce_sum(vector1, axis=0)  # Ищем сумму всех элементов

tensor_advanced_sum = tf.reduce_sum(tf.constant([[45, 2, 7],
                                                 [95, 35, 5],
                                                 [9, 56, 89]], shape=(3, 3), dtype=tf.int32), axis=1)  
# Axis влияет на то, будем ли мы считать сумму в столбцах или строках. В данном случае 1 - строки, 0 - столбцы

tensor_by_pow, tensor_sum, tensor_advanced_sum

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([   32,   243, 16807])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 54, 135, 154])>)

In [34]:
sample_vector = tf.constant([4, 23, 65, 741])
vector_idx = tf.constant([2, 3])
result_tensor = tf.gather(sample_vector, vector_idx)

result_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 65, 741])>

In [35]:
# Индексация с тензорами работает так же, как и с другими похожими типами данных в Python
tensor_indexation = tf.constant([[1, 2],
                                 [3, 4],
                                 [5, 6]])

tensor_indexation[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [36]:
tensor_indexation[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [37]:
# Reshaping
tensor_to_reshape = tf.range(9)
reshaped_tensor = tf.reshape(tensor_to_reshape, (3, 3))

reshaped_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [41]:
tensor_to_reshape2 = tf.range(7)
reshaped_tensor2 = tf.reshape(tensor_to_reshape2, (7, 1))

"""
Числа кортежа должны произведением давать кол-во элементов в данном тензоре
"""

reshaped_tensor2

<tf.Tensor: shape=(7, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])>

In [43]:
transposed_tensor = tf.transpose(tf.constant([[1, 2, 3],
                                              [4, 5, 6],
                                              [7, 8, 9]]))
"""
tf.transpose содержит параметр perm, который, возможно, и отвечает за то, чтобы транспонировать конкретные
измерения тензора
"""

transposed_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])>

In [ ]:
# Ссылка на источник - https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2